name: e37-exporter
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  # 生成镜像 Tag
  generate-tags:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    output:
      tags: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: 获取镜像的 Tag 信息
        id: get-version
        run: |
          echo "##[set-output name=version;]$(cat VERSION)"
  push-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: 登录镜像仓库网站
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GitHub 已不支持使用密码登录，这里应该使用从 https://github.com/settings/tokens 这里创建的 Token
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: 构建并推送容器镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/desistdaydream/e37-exporter:${{needs.generate-tags.outputs.version}}
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: 登录镜像仓库网站
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: 构建并推送容器镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: docker.io/lchdzh/e37-exporter:${{needs.generate-tags.outputs.version}}
